<?php

/**
 * Updated 30 Novemeber 2020
 */
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5e9d864accece',
        'title' => 'Generative Images Sidebar',
        'fields' => array(
            array(
                'key' => 'field_5f43ad62cd80f',
                'label' => 'Save SVG to Disk',
                'name' => 'gi_save_svg',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5f43ad93cd810',
                'label' => 'Save JPG to Disk',
                'name' => 'gi_save_jpg',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5f43ada8cd811',
                'label' => 'Save PNG to Disk',
                'name' => 'gi_save_png',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5f43addccd812',
                'label' => 'Attach new image to Post / Term',
                'name' => 'gi_save_post',
                'type' => 'select',
                'instructions' => '(This will disable and switch off after each update)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'choices' => array(
                    'none' => 'Do Not Update Post / Term',
                    'jpg' => 'Save JPG to Post/Term',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5e9d8655fd086',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<a href="https://londonparkour.com/zimage-generator/" target="_blank">Generator Page</a>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'generativeimages',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5e7ce9be8ec08',
        'title' => 'Generative Images v2',
        'fields' => array(
            array(
                'key' => 'field_5fbb97818d9c4',
                'label' => 'Dependencies',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5fbb9503697bf',
                'label' => 'Imagick',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<img src="/wp-content/plugins/andyp_pipeline_generative_images/src/acf/data/imagick.png" height="200px">
    <h2>Used to convert SVG -> PNG</h2>
    <b><p style="color:green">iMagick v3.4.4 installed </p></b>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5fbb9544697c0',
                'label' => 'Inkscape',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<img src="/wp-content/plugins/andyp_pipeline_generative_images/src/acf/data/inkscape.png" height="200px">
    <h2>Used to convert PNG -> JPG</h2>
    <b><p style="color:green">Inkscape Inkscape 0.92.5 (0.92.5+68) installed.</p></b>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5fbb9705e983b',
                'label' => 'Instance',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f43bb8aeb1cc',
                'label' => 'Instance',
                'name' => 'genimage_instance',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5f43bb2ed4882',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f43bb2ed4882',
                        'label' => 'Slug',
                        'name' => 'genimage_instance_slug',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f43ba90d487f',
                        'label' => 'Source',
                        'name' => 'genimage_instance_source',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'choices' => array(
                            'phpunit_test' => 'phpunit_test',
                            'phpunit_source_test2' => 'phpunit_source_test2',
                            'phpunit_test_post' => 'phpunit_test_post',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5f43babfd4880',
                        'label' => 'Filter',
                        'name' => 'genimage_instance_filter',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'choices' => array(
                            'reference_library_covers' => 'reference_library_covers',
                            'reference_library_taxonomy' => 'reference_library_taxonomy',
                            'corner_dots' => 'corner_dots',
                            'daily_top_four' => 'daily_top_four',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5f43bae1d4881',
                        'label' => 'Enabled',
                        'name' => 'genimage_instance_enabled',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5e7f0d8a7bb58',
                'label' => 'Source',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5fbd0e544b518',
                'label' => 'Source',
                'name' => 'genimage_source',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5fbd0ebf4b51a',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5fbd0ebf4b51a',
                        'label' => 'Source Slug',
                        'name' => 'genimage_source_slug',
                        'type' => 'text',
                        'instructions' => 'Unique identifier',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5fbd0e764b519',
                        'label' => 'Source Type',
                        'name' => 'genimage_source_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'choices' => array(
                            'get_post' => 'Post',
                            'get_taxonomy' => 'Taxonomy',
                            'get_query' => 'WP_Query',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'array',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5e7ce9cf1ccf1',
                        'label' => 'Post',
                        'name' => 'genimage_post',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fbd0e764b519',
                                    'operator' => '==',
                                    'value' => 'get_post',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '80',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'post_type' => '',
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 1,
                        'return_format' => 'object',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_5e804f159ed7b',
                        'label' => 'Article Taxonomy',
                        'name' => 'genimage_taxonomy',
                        'type' => 'taxonomy',
                        'instructions' => 'This is for the "Article Category" taxonomy only. Requires the "andyp_articleCategory_image" plugin to an image field to the taxonomy.',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fbd0e764b519',
                                    'operator' => '==',
                                    'value' => 'get_taxonomy',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '80',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'taxonomy' => 'articlecategory',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_5e80bfbc34265',
                        'label' => 'WP_Query',
                        'name' => 'genimage_query',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fbd0e764b519',
                                    'operator' => '==',
                                    'value' => 'get_query',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '80',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5e804ee89ed7a',
                'label' => 'Filters',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e8046ce7ef45',
                'label' => 'Filters',
                'name' => 'genimage_filters',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5f4df54c0f9dd',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f4df54c0f9dd',
                        'label' => '',
                        'name' => 'genimage_filter_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f4d38477c3c9',
                                'label' => 'Preview',
                                'name' => 'genimage_filter_preview',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_5f43a7db36f85',
                                'label' => 'Filter Slug',
                                'name' => 'genimage_filter_slug',
                                'type' => 'text',
                                'instructions' => 'Unique Identifier',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '70',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e804cc6ecde8',
                        'label' => 'Filter Description',
                        'name' => 'genimage_filter_description',
                        'type' => 'textarea',
                        'instructions' => 'Summary of the filter.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '60',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5f4ca9328b0d7',
                        'label' => 'Resize Width',
                        'name' => 'genimage_filter_resize_width',
                        'type' => 'number',
                        'instructions' => 'Optional',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5f4ca9628b0d8',
                        'label' => 'Resize Height',
                        'name' => 'genimage_filter_resize_height',
                        'type' => 'number',
                        'instructions' => 'Optional',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5e80472b7ef47',
                        'label' => 'Layers',
                        'name' => 'genimage_filter',
                        'type' => 'repeater',
                        'instructions' => 'Stack of SVG layers in order top to bottom.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => 'layers__wrap',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e8047497ef48',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Layer',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e8047497ef48',
                                'label' => 'Filter Name',
                                'name' => 'filter_name',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'choices' => array(
                                    'acf_post_tax_field' => 'acf_post_tax_field',
                                    'acf_post_term_field' => 'acf_post_term_field',
                                    'acf_term_field' => 'acf_term_field',
                                    'acf_term_field_definition' => 'acf_term_field_definition',
                                    'darken' => 'darken',
                                    'generate_shape' => 'generate_shape',
                                    'image' => 'image',
                                    'image_free' => 'image_free',
                                    'image_grid' => 'image_grid',
                                    'noise' => 'noise',
                                    'None' => 'None',
                                    'random_colour' => 'random_colour',
                                    'svg_definition' => 'svg_definition',
                                    'svg_element' => 'svg_element',
                                    'text' => 'text',
                                    'whiten' => 'whiten',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5e8047997ef49',
                                'label' => 'Filter Parameters',
                                'name' => 'filter_parameters',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 3,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fc386b6853a0',
                                'label' => 'Layer',
                                'name' => 'filter_layer',
                                'type' => 'clone',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'clone' => array(
                                    0 => 'field_5fc382d5fcb14',
                                ),
                                'display' => 'seamless',
                                'layout' => 'block',
                                'prefix_label' => 0,
                                'prefix_name' => 1,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5fc38b7e8ea78',
                        'label' => 'Layers',
                        'name' => 'filter_layer',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 1,
                        'clone' => array(
                            0 => 'field_5fc382d5fcb14',
                        ),
                        'display' => 'seamless',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5fbbc2bc11d5b',
                'label' => 'Results',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5fbbc2cb11d5c',
                'label' => '',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<table></table>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5e860d5f350ac',
                'label' => 'Help',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f48ae120dded',
                'label' => 'Help Group',
                'name' => 'genimage_help_group',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f48ae440ddef',
                        'label' => 'Filter Library',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5f4777823c93f',
                        'label' => 'Filter Library',
                        'name' => 'genimage_library',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5f4778c73c940',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f4778c73c940',
                                'label' => 'Filter Name',
                                'name' => 'genimage_library_filter_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5f4778ec3c941',
                                'label' => 'Filter Description',
                                'name' => 'genimage_library_filter_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '70',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5f4779123c942',
                                'label' => 'Example Parameter Input',
                                'name' => 'genimage_library_filter_example',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror ue__codemirror--scrollbars',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5f479f850bcc5',
                                'label' => 'Example Output',
                                'name' => 'genimage_library_filter_example_output',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror ue__codemirror--scrollbars',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5f48ae660ddf1',
                        'label' => 'Examples',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5f48ae7e0ddf2',
                        'label' => 'Examples',
                        'name' => 'genimage_examples',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5f48af89d03b3',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f48af89d03b3',
                                'label' => 'Title',
                                'name' => 'genimage_examples_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5f48ae9b0ddf3',
                                'label' => 'Description',
                                'name' => 'genimage_examples_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 12,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5f48aec40ddf4',
                                'label' => 'Example',
                                'name' => 'genimage_examples_example',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '70',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 12,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e8062b26be3b',
                        'label' => 'Debug',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e861d148d529',
                        'label' => 'Debug',
                        'name' => 'genimage_debug',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'ue__codemirror ue__codemirror--scrollbars',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 20,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5f48ae520ddf0',
                        'label' => 'Useful Links',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e804e63702aa',
                        'label' => 'Links',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'message' => '<code>[genimage]</code>
    
    <h4>Links</h4>
    <a href="http://apigen.juzna.cz/doc/WordPress/WordPress/class-WP_Post.html">WP_Post</a>
    <a href="http://apigen.juzna.cz/doc/WordPress/WordPress/class-WP_Term.html">WP_Term</a>
    <a href="https://developer.wordpress.org/reference/classes/wp_query/">WP_Query</a>
    
    <h4>Misc</h4>
    <a href="https://github.com/una/CSSgram/tree/master/source/scss">Instagram CSS filters</a>
    <a href="https://yoksel.github.io/svg-gradient-map/#/">DuoTone</a>
    <a href="http://pleeease.io/play/">Convert CSS filters to SVG</a>
    <a href="http://www.heropatterns.com/">Hero Patterns</a>
    <a href="http://yoksel.github.io/svg-filters/#/">SVG Filter builder</a>
    <a href="http://www.petercollingridge.co.uk/tutorials/svg/isometric-projection/">Isometric Transforms</a>
    <a href="https://github.com/jorgeatgu/fildrop/blob/master/demo.html">SVG Filter Reference</a>',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f43aa600bba5',
                'label' => 'Hooks',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f43aa690bba6',
                'label' => 'Hook',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<h1>Run via a wordpress filter.</h2>
    
    <pre>apply_filter(\'genimage_get_instance\', $filter_slug, $source_objects, $saves_array, $dimensions); </pre>
    
    <h3>Description</h3>
    You can run an instance of the generative image plugin via the <code>\'genimage_get_instance\'</code> filter.
    <br/>
    
    <h3>Parameters</h3>
    
    <h4><pre style="display:inline; color: #fff; background: #242424; padding:2px;">(string) $filter_slug</pre></h4>
    <p>slug name of the filter to run. i.e. <code>\'test_filter\'</code></p>
    
    <br/>
    
    <h4><pre style="display:inline; color: #fff; background: #242424; padding:2px;">(array) $source_objects</pre></h4>
    <p>An array of WP_Term / WP_Post source objects. i.e. <code>[ 0 => WP_Post, 1 => WP_Post, 2 => WP_Post ]</code></p>
    
    <br/>
    
    <h4><pre style="display:inline; color: #fff; background: #242424; padding:2px;">(array) $saves_array</pre></h4>
    <p>Which conversions to run. i.e. <code>[ \'svg\' => true,	\'png\' => false, \'jpg\' => true ]</code></p>
    
    <br/>
    
    <h4><pre style="display:inline; color: #fff; background: #242424; padding:2px;">(array) $dimensions</pre></h4>
    <p>Optional variable that will change the size of the output SVG. Width, Height in pixels. i.e. <code>[ 0 => \'640\', 1 => \'480\' ]</code></p>
    
    <br/>
    
    <h3>Returned</h3>
    <p>Returns <code>true</code> on success.</p>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'generativeimages',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;