<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5e7ce9be8ec08',
        'title' => 'Generative Images',
        'fields' => array(
            array(
                'key' => 'field_5e805049391c2',
                'label' => 'Source',
                'name' => 'genimage_source',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'choices' => array(
                    'get_article' => 'Single Article',
                    'get_category' => 'Article Category',
                    'get_query' => 'Query',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'Single Post',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5e86d03643437',
                'label' => 'Save Post / Term',
                'name' => 'gi_save_post',
                'type' => 'select',
                'instructions' => 'Note - This will only write once and the option is switched off after one rewrite of the image file.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'choices' => array(
                    'none' => 'Do Not Update',
                    'jpg' => 'JPG (switches off each time!)',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5e86d0c58263e',
                'label' => 'Save SVG',
                'name' => 'gi_save_svg',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '10',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e86d0ea8263f',
                'label' => 'Save JPG',
                'name' => 'gi_save_jpg',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '10',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e86d0f982640',
                'label' => 'Save PNG',
                'name' => 'gi_save_png',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '10',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e7f0d8a7bb58',
                'label' => 'Single Article',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e7ce9cf1ccf1',
                'label' => 'Article',
                'name' => 'genimage_article',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'post_type' => array(
                    0 => 'article',
                    1 => 'post',
                    2 => 'attachment',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
            ),
            array(
                'key' => 'field_5e8046ce7ef45',
                'label' => 'Filters',
                'name' => 'genimage_filters',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5e804cc6ecde8',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e8046fc7ef46',
                        'label' => 'Enabled',
                        'name' => 'enabled',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5e804cc6ecde8',
                        'label' => 'Filter Name',
                        'name' => 'filter_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '80',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5e80472b7ef47',
                        'label' => 'Layers',
                        'name' => 'genimage_filter',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e8047497ef48',
                                'label' => 'Filter Name',
                                'name' => 'filter_name',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'choices' => array(
                                    'none' => 'none',
                                    'acf_post_tax_field' => 'acf_post_tax_field',
                                    'acf_post_term_field' => 'acf_post_term_field',
                                    'darken' => 'darken',
                                    'generate_shape' => 'generate_shape',
                                    'image' => 'image',
                                    'image_free' => 'image_free',
                                    'noise' => 'noise',
                                    'random_colour' => 'random_colour',
                                    'svg_definition' => 'svg_definition',
                                    'svg_element' => 'svg_element',
                                    'text' => 'text',
                                    'whiten' => 'whiten',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5e8047997ef49',
                                'label' => 'Filter Parameters',
                                'name' => 'filter_parameters',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 3,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5e804ee89ed7a',
                'label' => 'Article Category',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e804f159ed7b',
                'label' => 'Category',
                'name' => 'genimage_category',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'taxonomy' => 'articlecategory',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5e804f4b9ed7c',
                'label' => 'Filters',
                'name' => 'genimage_category_filters',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5e804f4b9ed7e',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e804f4b9ed7d',
                        'label' => 'Enabled',
                        'name' => 'enabled',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5e804f4b9ed7e',
                        'label' => 'Filter Name',
                        'name' => 'filter_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '80',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5e804f4b9ed7f',
                        'label' => 'Layers',
                        'name' => 'genimage_filter',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e804f4b9ed80',
                                'label' => 'Filter Name',
                                'name' => 'filter_name',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'choices' => array(
                                    'none' => 'none',
                                    'acf_term_field' => 'acf_term_field',
                                    'acf_term_field_definition' => 'acf_term_field_definition',
                                    'darken' => 'darken',
                                    'generate_shape' => 'generate_shape',
                                    'image' => 'image',
                                    'image_free' => 'image_free',
                                    'noise' => 'noise',
                                    'random_colour' => 'random_colour',
                                    'svg_definition' => 'svg_definition',
                                    'svg_element' => 'svg_element',
                                    'text' => 'text',
                                    'whiten' => 'whiten',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5e804f4b9ed81',
                                'label' => 'Filter Parameters',
                                'name' => 'filter_parameters',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 3,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5e80be1698a28',
                'label' => 'Query',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e80bfbc34265',
                'label' => 'Query Statement',
                'name' => 'query_statement',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 20,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5e80be9998a30',
                'label' => 'Filters',
                'name' => 'genimage_query_filters',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'collapsed' => 'field_5e80be9998a32',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e80be9998a31',
                        'label' => 'Enabled',
                        'name' => 'enabled',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5e80be9998a32',
                        'label' => 'Filter Name',
                        'name' => 'filter_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '80',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5e80be9998a33',
                        'label' => 'Layers',
                        'name' => 'genimage_filter',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e80be9998a34',
                                'label' => 'Filter Name',
                                'name' => 'filter_name',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'choices' => array(
                                    'none' => 'none',
                                    'acf_post_tax_field' => 'acf_post_tax_field',
                                    'acf_post_term_field' => 'acf_post_term_field',
                                    'darken' => 'darken',
                                    'generate_shape' => 'generate_shape',
                                    'image' => 'image',
                                    'image_free' => 'image_free',
                                    'noise' => 'noise',
                                    'random_colour' => 'random_colour',
                                    'svg_definition' => 'svg_definition',
                                    'svg_element' => 'svg_element',
                                    'text' => 'text',
                                    'whiten' => 'whiten',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5e80be9998a35',
                                'label' => 'Filter Parameters',
                                'name' => 'filter_parameters',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 3,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5e8062b26be3b',
                'label' => 'Notes',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e861d148d529',
                'label' => 'Note Group',
                'name' => 'note_group',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e861d858d52a',
                        'label' => 'Elements',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e8062c46be3c',
                        'label' => 'Element Notes',
                        'name' => 'element_notes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e80631740862',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e80631740862',
                                'label' => 'Title',
                                'name' => 'el_note_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5e8062dd6be3d',
                                'label' => 'Quick Note',
                                'name' => 'el_quick_note',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e861dc08d52b',
                        'label' => 'SVGs',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e861e02fef8e',
                        'label' => 'SVG Notes',
                        'name' => 'svg_notes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e861e02fef8f',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e861e02fef8f',
                                'label' => 'Title',
                                'name' => 'svg_note_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5e861e02fef90',
                                'label' => 'Quick Note',
                                'name' => 'svg_quick_note',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e861dce8d52c',
                        'label' => 'Filters',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e861e0cfef91',
                        'label' => 'Filter Notes',
                        'name' => 'filter_notes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e861e0cfef92',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e861e0cfef92',
                                'label' => 'Title',
                                'name' => 'filter_note_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5e861e0cfef93',
                                'label' => 'Quick Note',
                                'name' => 'filter_quick_note',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e861f1e64193',
                        'label' => 'Queries',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e861f3364195',
                        'label' => 'Query Notes',
                        'name' => 'query_notes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e861f3364196',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e861f3364196',
                                'label' => 'Title',
                                'name' => 'query_note_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5e861f3364197',
                                'label' => 'Quick Note',
                                'name' => 'query_quick_note',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5e861f5d64198',
                        'label' => 'Quick Notes',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5e861f6e64199',
                        'label' => 'Quick Notes',
                        'name' => 'quick_notes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5e861f6e6419a',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5e861f6e6419a',
                                'label' => 'Title',
                                'name' => 'quick_note_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5e861f6e6419b',
                                'label' => 'Quick Note',
                                'name' => 'quick_quick_note',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '80',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5e860d5f350ac',
                'label' => 'Help',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e7faba06f3cf',
                'label' => 'Notes',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<table>
    
        <head style="background-color: #E0E0E0;">
            <tr><td>layer type</td><td>description</td><td>parameter</td></tr>
        </thead>
    
        <tr>
             <td><code>text</code></td>
             <td>Output text with substituted fields.</td>
             <td>Text that uses moustache {{post_title}} tags or any other WP_Post / WP_Term item<br/>Also have <code>us:</code> prefix for Upper Case text and <code>hy:</code> for hypen replacement for newlines.</td>
        </tr>
    
        <tr>
            <td><code>taxonomy_acf</code></td>
            <td>Text with the use of ACF values on the (first) WP_Term (articlecategory)</td>
            <td>Use moustaches {{name}} ACF fields of the WP_Term (articlecategory).</td>
        </tr>
    
        <tr>
            <td><code>image</code></td>
            <td>Use the selected post\'s featured image.</td>
            <td>The parameter is any additional image tag attributes like <code>filter</code> or <code>id</code>, etc... you wish to insert</td>
        </tr>
    
        <tr>
            <td><code>image_free</code></td>
            <td>Image with no width or height defined</td>
            <td>The parameter can insert any (including widht/height) parameters into it.</td>
        </tr>
    
        <tr>
            <td><code>elements</code></td>
            <td>Anything you want to manually add into the SVG</td>
            <td>Text of anything you want to add in. use g, text, rect, svg, image, etc...</td>
        </tr>
    
        <tr>
            <td><code>noise</code></td>
            <td>Insert a \'noise\' image layer over everything below it.</td>
            <td><code>[Opacity],[filename]</code>. Opacity level 0 to 1. Filename is (optional) - must be a LOCAL file.</td>
        </tr>
    
     <tr>
            <td><code>random_colour</code></td>
            <td>Randomly generate a hex colour and inserts it as a definition.</td>
            <td>ID of the random colour.</td>
        </tr>
    
     <tr>
            <td><code>none</code></td>
            <td>Diable the layer</td>
            <td>N/A</td>
        </tr>
    
     <tr>
            <td><code>svg_definition</code></td>
            <td>Add a new definition into the SVG</td>
            <td>Text of the definition</td>
        </tr>
    
     <tr>
            <td><code>darken</code></td>
            <td>Adds a pure black layer</td>
            <td>Opacity level 0 - 1</td>
        </tr>
    
     <tr>
            <td><code>whiten</code></td>
            <td>Adds a pure white layer</td>
            <td>Opacity level 0 - 1</td>
        </tr>
    
    <tr>
            <td><code>generate_shape</code></td>
            <td>Creates generated random shapes</td>
            <td>Lots of parameters!</td>
        </tr>
    
    </table>',
                'new_lines' => '',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5e804e63702aa',
                'label' => 'Shortcodes',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '<code>[andyp_gen_image]</code>
    
    <h4>Links</h4>
    <a href="http://apigen.juzna.cz/doc/WordPress/WordPress/class-WP_Post.html">WP_Post</a>
    <a href="http://apigen.juzna.cz/doc/WordPress/WordPress/class-WP_Term.html">WP_Term</a>
    <a href="https://developer.wordpress.org/reference/classes/wp_query/">WP_Query</a>
    
    <h4>Misc</h4>
    <a href="https://github.com/una/CSSgram/tree/master/source/scss">Instagram CSS filters</a>
    <a href="https://yoksel.github.io/svg-gradient-map/#/">DuoTone</a>
    <a href="http://pleeease.io/play/">Convert CSS filters to SVG</a>
    <a href="http://www.heropatterns.com/">Hero Patterns</a>
    <a href="http://yoksel.github.io/svg-filters/#/">SVG Filter builder</a>
    <a href="http://www.petercollingridge.co.uk/tutorials/svg/isometric-projection/">Isometric Transforms</a>
    <a href="https://github.com/jorgeatgu/fildrop/blob/master/demo.html">SVG Filter Reference</a>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'generativeimages',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;